// Generated by `wat2wasm test.wat --output=- | base64`
let wasmBuffer =
  "AGFzbQEAAAABDAJgAn9/AX9gAX8BfwMDAgABBQMBAAEGBgF/AUEACwcNAgNzZXQAAANnZXQAAQocAhIAIwAgATYCACMAQQFqJAAjAAsHACAAKAIACw==";
let arrayBuffer = Uint8Array.from(atob(wasmBuffer), (letter) =>
  letter.charCodeAt(0)
);
let wasm = new WebAssembly.Instance(new WebAssembly.Module(arrayBuffer));

class Secret {
  constructor(secret) {
    this.secretId = wasm.exports.set(this.secretId, secret);
  }

  get() {
    return wasm.exports.get(this.secretId);
  }
}
